### ISSUE TITLE
Scanner freezes

### ISSUE THREAD

**Issue by kixxu** [h0nde/roblox-group-scanner-v2#5]
So, when i run scanner after 10/30 seconds it freezes.
Week ago it worked without any problems.

**Comment by RyanHeDev** [comment]
sometimes this kind of things get patched

**Comment by h0nde** [comment]
Ignore the comment above, the bot still works fine on my end. What device are you running the tool on? Have you tried decreasing the number of workers?

**Comment by kixxu** [comment]
I run it in my main computer. I tried decreasing workers from 16 to 8, 4, 1 but it still freezes.

**Comment by kixxu** [comment]
PC Specs:
PSU: Chieftec 500W
CPU: AMD Ryzen 2400g
GPU: ASUS Radeon RX 570 STRIX OC 8GB
RAM: Goodram 16GB 2666Mhz

**Comment by h0nde** [comment]
It could be a problem with your network connection, or possibly anti-malware software.

**Comment by h0nde** [comment]
I have no clue then.
